config/routes.rb
BlogArticle::Application.routes.draw do

 resources :articles do 
   member do
post :notify_friend
end
	resources :comments
     end
     resources :users
     resources :profiles
     resource :session
root :to => "articles#index", :as => 'arti'
match '/login' => "sessions#new", :as => "login"
match '/logout' => "sessions#destroy", :as => "logout"

end

app/models/article.rb
class Article < ActiveRecord::Base
validates :title, :body, :location, :price, :presence=> true
validates :title, :uniqueness=>true
has_many :comments
has_and_belongs_to_many :categories
belongs_to :user
scope :published, where("articles.published_at IS NOT NULL")
scope :draft, where("articles.published_at IS NULL")
scope :recent, lambda { published.where("articles.published_at > ?",1.week.ago.to_date)}
scope :where_title, lambda { |term| where("articles.title LIKE ?", "%#{term}%") }

def published?
published_at.present?
end
def owned_by?(owner)
return false unless owner.is_a? User
user == owner
end


end

app/models/category.rb
class Category < ActiveRecord::Base
has_and_belongs_to_many :articles
default_scope order('categories.name')	
end

app/models/comment.rb
class Comment < ActiveRecord::Base
validates :email, :presence => true, :format => { :with => /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i }
validates :post, :presence => true
validate :arti
validates :body, :presence => true, :length => { :within => 5..50 }
belongs_to :article
def arti
errors.add(:article_id, "is not published yet") if article && !article.published?
end


end

app/models/comment_observer.rb
class CommentObserver < ActiveRecord::Observer
	def after_create(comment)
Notifier.comment_added(comment).deliver
end

end

app/models/profile.rb
class Profile < ActiveRecord::Base
belongs_to :user
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
attr_accessor :password

has_one :profile
has_many :articles, :order => 'published_at DESC', :dependent => :nullify
has_many :replies, :through => :articles, :source => :comments
default_scope order('users.email')
validates :email, :presence => true,:format => { :with => /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i }, :length => { :within => 5..50 }, :uniqueness => true
validates :password, :confirmation => true, :length => { :within => 4..20 }, :presence => true, :if => :password_required?
before_save :encrypt_new_password

def self.authenticate(email, password)
user = find_by_email(email)
return user if user && user.authenticated?(password)
end

def authenticated?(password)
self.hashed_password == encrypt(password)
end

protected
def encrypt_new_password
return if password.blank?
self.hashed_password = encrypt(password)
end

def password_required?
hashed_password.blank? || password.present?
end

def encrypt(string)
Digest::SHA1.hexdigest(string)
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  protected
# Returns the currently logged in user or nil if there isn't one
def current_user
return unless session[:user_id]
@current_user ||= User.find_by_id(session[:user_id])
end
# Make current_user available in templates as a helper
helper_method :current_user
# Filter method to enforce a login requirement
# Apply as a before_filter on any controller you want to protect
def authenticate
logged_in? ? true : access_denied
end
# Predicate method to test for a logged in user
def logged_in?
current_user.is_a? User
end
# Make logged_in? available in templates as a helper
helper_method :logged_in?
def access_denied
redirect_to login_path, :notice => "Please log in to continue" and return false
end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
before_filter :authenticate, :except => [:index, :show, :notify_friend]

  def index
	@article=Article.all
  end

  def new
	@article=Article.new # To view the form for new object
  end

  def create
	@article=Article.new(params[:article]) #To create a new article
	respond_to do |format|
	@article.user_id=current_user.id
	if @article.save
	format.html {redirect_to (arti_url, :notice => "Article successfully created.")}
        else
        format.html { render :action => "new" }
	end
	end
	end

  def show
	@article=Article.find(params[:id])
  end 

  def edit
	@article=Article.find(params[:id])
  end

  def update
	@article=Article.find(params[:id])
	respond_to do |format|
	if @article.update_attributes(params[:article])
	format.html {redirect_to (arti_url, :notice => "Article successfully updated.")}
        else
        format.html { render :action => "edit" }
	end
	end
	end
  
  def destroy
      @article=Article.find(params[:id])
      respond_to do |format|
	if @article.destroy
	format.html {redirect_to (arti_url, :notice => "Article successfully deleted.")}
	end
	end
	end
def notify_friend
@article = Article.find(params[:id])
Notifier.email_friend(@article, params[:name], params[:email]).deliver
redirect_to @article, :notice => "Successfully sent a message to your friend"
end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_filter :authen

def create
@comment = @article.comments.new(params[:comment])
if @comment.save
respond_to do |format|
format.html { redirect_to @article, :notice => 'Thanks for your comment' }
format.js
end
else
respond_to do |format|
format.html { redirect_to @article, :alert => 'Unable to add comment' }
format.js { render 'fail_create.js.erb' }
end
end
end


def destroy
@comment = @article.comments.find(params[:id])
@comment.destroy
redirect_to @article, :notice => 'Comment deleted'
end

private
def authen
@article = Article.find(params[:article_id])
end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

	def new
		@profile=Profile.new
	end
	def create
		@profile=Profile.new(params[:profile])
			@profile.user_id=current_user.id
		if @profile.save
		redirect_to arti_url
	else
	render :new
	end
	end
	
	def edit
		@profile=Profile.find_by_user_id(current_user.id)
	end
	def update
		@profile=Profile.find_by_user_id(current_user.id)
		p @profile
		if @profile.update_attributes(params[:profile])
		redirect_to arti_url, :notice => 'Updated user information successfully.'
		else
		render :edit
		end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def create
if user = User.authenticate(params[:email], params[:password])
session[:user_id] = user.id
if user.profile.present?
redirect_to arti_url, :notice => "Logged in successfully"
else
redirect_to new_profile_path, :noitce => "you have created successfully"
end
else
flash.now[:alert] = "Invalid login/password combination"
render :action => 'new'
end
end
def destroy
reset_session
redirect_to arti_url, :notice => "You successfully logged out"
end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate, :only => [:edit, :update]

  def new
   @user=User.new
  end

  def create
	@user=User.create(params[:user])
	if @user.save
	redirect_to articles_path
	else
	render :action => "new"
	end
  end

  def edit
	@user = User.find(params[:id])
  end

  def update
	@user = User.find(params[:id])
	if @user.update_attributes(params[:user])
	redirect_to articles_path
	else
	render :action => 'edit'
	end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<script="text/javascript"></script>
<script>
function article()
{
alert("Edit your aticle");
}
</script>
<%= div_for article do %>
<h3>
<%= link_to article.title, article %>
<% if article.owned_by? current_user %>
<div class='actions'>
<%= link_to "Edit", edit_article_path(article),:onclick=>"article()" %>
<%= link_to "delete", article, :confirm =>"Are You Sure?", :method => :delete %>
</div>
<% end %>
</h3>
<%= simple_format raw(article.body) %>
<% end %>

app/views/articles/_edit.html.erb
<%= form_for(@prod) do |f|%>
<div class="field">
<%= f.label:ProductName%>
<%= f.text_field:product%>
</div>

<div class="field">
<%= f.label:Price%>
<%= f.text_field:price%>
</div>

<div class="field">
<%= f.label:Available_Quantity%>
<%= f.text_field:quantity%>
</div>

<div class="field">
<div class="action"><%= f.submit%></div>
</div>
<%end%>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f|%>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
<%= f.label:title%>
<%= f.text_field:title%>
</div>

<div class="field">
<%= f.label:Price%>
<%= f.text_field:price%>
</div>

<div class="field">
<%= f.label:loaction%>
<%= f.text_field:location%>
</div>

<div class="field">
<%= f.label:body%>
<%= f.text_area:body,:rows => 5, :cols => 30%>
</div>

<div class="field">
<%= f.label:published_at%>
<%= f.date_select :published_at%>
<%=f.time_select :published_at %>
</div>
<div class="field">
<%= f.label "Categories" %><br />
<% for category in Category.all %>
<%= check_box_tag 'article[category_ids][]', category.id, @article.category_ids.include?(category.id), :id => dom_id(category) %>
<%= label_tag dom_id(category), category.name, :class => "check_box_label" %>
<% end %>
</div>

<div class="field">
<div class="action"><%= f.submit%></div>
</div>

<%end%>

app/views/articles/_notify_friend.html.erb
<%= form_tag(notify_friend_article_path(@article), :id => 'notify_friend_form', :style => 'display:none') do %>
<div class="field">
<%= label_tag :name, 'Your name' %><br />
<%= text_field_tag :name %>
</div>
<div class="field">
<%= label_tag :email, "Your friend's email" %><br />
<%= text_field_tag :email %>
</div>
<div class="actions">
<%= submit_tag 'Send' %> or
<%= link_to 'Cancel', '#', :onclick => "$('#notify_friend_form').slideUp()" %>
</div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', arti_url %> |
<%= link_to 'Back', arti_url %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
<div id="articles">
<%= render @article %>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>|

<%= link_to 'Back', arti_url %>

app/views/articles/new.js.erb
$("<%= escape_javascript render(:file => 'articles/new.html.erb') %>").insertBefore('#one');

app/views/articles/show.html.erb
<script="text/javascript"></script>
<script>
function article()
{
alert("Edit your aticle");
}
</script>

<%= render @article %>s	
<h3>Comments</h3>
<%= render @article.comments %>
<%= render :file => 'comments/new' %>
<%= link_to 'Email a friend', '#', :onclick => "$('#notify_friend_form').slideDown()" %>
<%= render 'notify_friend' %>

<%= link_to 'Edit', edit_article_path(@article), :onclick=>"article()" %> |
<%= link_to 'Back', arti_url %>
<%= link_to "new comment", new_article_comment_path(@article, :format => :js), :remote => true, :id => 'new_comment_link' %>

app/views/comments/_comment.html.erb
<%= div_for comment do %>
<h3>
<%= comment.post %> &lt;<%= comment.email %>&gt; said:
<%= link_to 'Delete', [@article, comment], :confirm => 'Are you sure?', :method => :delete %>
</h3>
<%= comment.body %>
<% end %>

app/views/comments/create.js.erb
$('#comments').append("<%= escape_javascript(render(@comment)) %>");
$('#new_comment')[0].reset();

app/views/comments/fail_create.js.erb
alert("<%= @comment.errors.full_messages.to_sentence %>");

app/views/comments/new.html.erb
<%= form_for([@article, @article.comments.new], :remote => true, :html => {:style => 'display: none;'}) do |f| %>
<div class="field">
<%= f.label :name %><br />
<%= f.text_field :post %>
</div>
<div class="field">
<%= f.label :email %><br />
<%= f.text_field :email %>
</div>
<div class="field">
<%= f.label :body %><br />
<%= f.text_area :body, :rows => 5, :cols => 30%>
</div>
<div class="actions">
<%= f.submit %>
</div>
<% end %>

app/views/comments/new.js.erb
$("<%= escape_javascript render(:file => 'comments/new.html.erb') %>").insertAfter('#comments');
$('#new_comment').slideDown();
$('#new_comment_link').hide();

app/views/layouts/application.html.erb
<head>
<link href="/assets/style.css" rel="stylesheet" type="text/css" />
<%= stylesheet_link_tag    "application" %>
<%= javascript_include_tag 'jquery-1.4.2.min', 'rails', 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="header">
<h1><%= link_to "Blog_Article", arti_url %></h1>
<div id="user_bar">
<% if logged_in? %>
<%= link_to "New Article", new_article_path, :remote=>true, :format=>:js%> |
<%= link_to "Edit Password", edit_user_path(current_user), :remote=>true, :format=>:js%> |
<%= link_to "Profile", edit_profile_path(current_user.id) %> |
<%= link_to "Logout", logout_path %> 
<% else %>
<%= link_to "Login", login_path %>
<%= link_to "New User", new_user_path %>
<% end %>
</div>
</div>
<div id="main">
<%= content_tag(:p, notice, :class => 'notice') if notice.present? %>
<%= content_tag(:p, alert, :class => 'alert') if alert.present? %>
<div id="one">
<%= yield %>
</div>
</div>
<div id="footer">
A simple blog built for the book
<a href="http://beginningrails.com">Beginning Rails 3</a>
</div>

</body>
</html>

app/views/notifier/email_friend.text.erb
Your friend <%= @sender_name %> thinks you may like the following article:
<%= @article.title %>: <%= article_url(@article, :host => "localhost:3000") %>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |profile| %><br>
<div class="field"><%= profile.label:Name%><%= profile.text_field:name%></div>
<div class="field"><%= profile.label:Color%><%= profile.text_field:color%></div>
<div class="field"><%= profile.label:Biodata%><%= profile.text_field:biodata%></div>
<div class="field"><%= profile.label:twitter%><%= profile.text_field:twitter%></div>
<div class="field"><%= profile.label:DOB%><%= profile.text_field :birthday, :class=>"datepick"%></div>
<%= profile.submit%>
<%end%>
<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css"">
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js"></script>
<script>
      $(function() {
              $( ".datepick" ).datepicker();
      });
</script>

app/views/profiles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>|

<%= link_to 'Back', arti_url %>

app/views/profiles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>|

<%= link_to 'Back', arti_url %>

app/views/users/_user.html.erb
	<script type="text/javascript" src="/assets/jquery-1.7.1.js"></script>
<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
<script type="text/javascript" language="javascript">
$(document).ready(function() {
$("#dialog").hide();
	$("#btn").click(function(){
	$("#dialog").dialog();
		});
  });
  </script>

<input type="button" id="btn" value="Click"/>
<div id="dialog" title="New User Sign Up">
<%=form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
Email <%=f.text_field :email%><br/>
Password<%=f.password_field :password%>
Password Confirmation<%=f.password_field :password_confirmation%>
<%=f.submit%>
<%end%>	
</div>

app/views/users/edit.html.erb
<h1>New user</h1>
<%= render @user %>
<%= link_to 'Back', arti_url %>

app/views/users/edit.js.erb
$("<%= escape_javascript render(:file => 'users/edit.html.erb') %>").insertBefore('#one');
$("#user_bar").hide();

app/views/users/new.html.erb
<h1>New user</h1>
<%= render 'user' %>
<%= link_to 'Back', arti_url %>